version: "3.8"

services:
  painel:
    image: nginx:alpine
    container_name: dpsp-painel
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped